# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71790badb7ebbbabe30460caba353cd27b6c3de2164d7f2a6e3c493038f22116b7f15237a43974b29d4f933cb6398cbe39cd9a450b87bfbaa82ff8a7055c633b

test:
  secret_key_base: 156927cb83e5602175f4ea36e84b410f2e54a41407ec1e51144580a4f8ee21d7f23e59f68a2591a126dc14ed1e8ba0676e8e88806f33b27bc9d8a46fad510daa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
